### PR TITLE
Introduced a class Door and remove Global variable - the root of the …

### PR DESCRIPTION
**Pull request by dfurmans**
…mutability evil

### CODE REVIEW

**Comment by dfurmans** [comment]
definitively we should remove any global variable state - like door and config.

**Comment by dfurmans** [comment]
Github Slack integration - add comments - checkin

**Comment by dfurmans** [comment]
test

**Comment by manfred-ackermann** [comment]
I totally reworked the before version.

**Comment by dfurmans** [comment]
Oki doki

**Pull request closed without merging**
